services:
    seiscomp:
        image: ghcr.io/fmassin/seiscomp-docker:main
        container_name: seiscomp-docker
        hostname: seiscomp-in-a-Docker
        build: seiscomp-docker
        platform: linux/amd64 # for M1 users
        ports:
            - "2224:22"
        extra_hosts:
          - "host.docker.internal:host-gateway"
        restart: unless-stopped
        volumes:
            - seiscompsysop:/home/sysop
            - $SEISCOMP_ROOT/etc/:/home/sysop/.seiscomp:ro
            - $SEISCOMP_ROOT/share/maps:/opt/seiscomp/share/maps:ro
            - $SEISCOMP_ROOT/share/nll:/opt/seiscomp/share/nll:ro
            - $SEISCOMP_ROOT/share/hypo71:/opt/seiscomp/share/hypo71:ro
        tty: true        
volumes:
  seiscompsysop:
